title: Zesty.io Platform Status 
description: A Zesty.io service(s) status report page
google_analytics: 
theme: jekyll-theme-cayman
collections:
  incidents:
    output: true
    permalink: /incidents/:title/

