title: Zesty.io Platform Status 
description: Zesty service status report page
google_analytics: 
theme: jekyll-theme-cayman
collections:
  incidents:
    output: true
    permalink: /incidents/:year:month:day:hour:minute:second/

plugins:
  - jekyll-paginate

paginate: 5 # The number of posts per page
paginate_path: "/page:num/"

